### ISSUE TITLE
500 internal error.

### ISSUE THREAD

**Issue by gobijan** [figo-connect/node-figo#48]
**Code:**

    var figo = require('figo');
    var access_token = "ASHWLIkouP2O6_bgA2wWReRhletgWKHYjLqDaqb0LFfamim9RjexTo22ujRIP_cjLiRiSyQXyt2kM1eXU2XLFZQ0Hro15HikJQT_eNeT_9XQ";
    var session = new figo.Session(access_token);

    session.get_transactions(null, function(error, transactions) {
      if (error) {
        console.error(error);
      } else {
        transactions.forEach(function(transaction) {
          // Do whatever you want
          console.log(transaction.name);
        });
      }
    });

**Error:**

    info:  status_code=500, path=/rest/transactions?count=1000&offset=0&include_pending=0, code=500, group=null, name=HTTPInternalServerError, message=Internal server error, , description=null
    { FigoError
        at IncomingMessage.<anonymous> (/Users/bijan/workspace/demos/figo-node/node_modules/figo/lib/figo.js:149:23)
        at emitNone (events.js:111:20)
        at IncomingMessage.emit (events.js:208:7)
        at endReadableNT (_stream_readable.js:1056:12)
        at _combinedTickCallback (internal/process/next_tick.js:138:11)
        at process._tickCallback (internal/process/next_tick.js:180:9)
      name: 'FigoError',
      error: 
       { code: 500,
         group: null,
         name: 'HTTPInternalServerError',
         message: 'Internal server error',
         data: {},
         description: null } }

**Somethings wrong on your end?**

**Comment by steinke** [comment]
Hi 
can you please provide the user id or username via email to support@figo.io 
Or did you use the demo user?
I don't think that this is a node sdk issue 
Thx
Bianca
